source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'WorksStoryboard_Example', :exclusive => true do
  pod "WorksStoryboard", :path => "../"
end

target 'WorksStoryboard_Tests', :exclusive => true do
  pod "WorksStoryboard", :path => "../"

  
end
