source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'WorksStoryboarpod repo push vcube --sources='git@bitbucket.org:v-cube/repository_podspecs.git,https://github.com/CocoaPods/Specs' --private --allow-warnings QuickCameraWidget.podspecd_Example', :exclusive => true do
  pod "WorksStoryboard", :path => "../"
end

target 'WorksStoryboard_Tests', :exclusive => true do
  pod "WorksStoryboard", :path => "../"

  
end
